### ISSUE TITLE
Replication set connections ?

### ISSUE THREAD

**Issue by fruitl00p** [kingsquare/connect-mongo-memory#2]
Any chance this library can be updated to newer mongo-connect packages? I cant connect to a replication set uri using this old version of mongo-connect

thnx

**Comment by Reggino** [comment]
Switched to Redis myself, sorry. A PR will be evaluated though. :dancer:

**Comment by fruitl00p** [comment]
thanks, but no thanks, will ditch this in favour of Redis myself :) :dancer: :sheep:
